### ISSUE TITLE
Confused about FrameAddress packing

### ISSUE THREAD

**Issue by anweiss** [eminence/lifx#11]
Been reading through the codebase and it's unclear to me why `2` is being added in this line: https://github.com/eminence/lifx/blob/08526bb6bb260be75fa1f5e90904f1643050fff2/lifx-core/src/lib.rs#L1855

Isn't `ack_required` simply a 1 bit bool?

**Comment by eminence** [comment]
Take a look at these docs:  https://lan.developer.lifx.com/docs/packet-contents#frame-address

It shows that the `res_required`, `ack_required`, and `reserved` fields are all packed into the same 1 byte octet

**Comment by anweiss** [comment]
Hmm, I guess I'm still a bit confused because in these lines for `Frame`:

https://github.com/eminence/lifx/blob/08526bb6bb260be75fa1f5e90904f1643050fff2/lifx-core/src/lib.rs#L1794-L1795

only a `1` is being added if `tagged` and/or `addressable` are `true` ... and `protocol` (bits 0-3), `addressable`, `tagged` and `origin` are all packed into the same 1 byte octet as well.

Unless for `FrameAddress` it could also be represented as follows?

```rust
let b: u8 = (self.reserved2 << 2);
b += if self.ack_required { 1 } else { 0 } << 2;
b += if self.res_required { 1 } else { 0 };
```

And apologies in advance as my knowledge of some of these concepts is a bit rusty. Thanks!

**Comment by eminence** [comment]
> Unless for `FrameAddress` it could also be represented as follows?

You've got the right idea, except it would be:

```rust
b += if self.ack_required { 1 } else { 0 } << 1;
```

Since `1 << 1 == 2`

Another way to have written this is:

```rust
let mut b = self.reserved2 << 2; // reserved2 becomes the upper 6 bits (bits 2 through 7)
if self.ack_required {
    b |= 0b10; // set bit 1
}
if self.res_required {
    b |= 0b01; // set bit 0
}
```

**Comment by brianmay** [comment]
I think this probably can be closed.

The argument could be made that consistency is desirable, but I think this is a low priority.
