### ISSUE TITLE
please release new code

### ISSUE THREAD

**Issue by brianmay** [eminence/lifx#13]
It looks like this message is not implemented yet.

This is similar to the `StateExtendedColorZones` 512 which is implemented, only a bit different.

**Comment by brianmay** [comment]
My mistake. This is implemented in master (#5), but that was never released.

Please can we have a new release?

Last release was almost a year ago.

**Comment by eminence** [comment]
Sure, I'll work on a new release this weekend

**Comment by eminence** [comment]
`v0.4.0` is now released on crates.io
