### ISSUE TITLE
handling of reserved fields

### ISSUE THREAD

**Issue by brianmay** [eminence/lifx#14]
Not sure about the handling of reserved fields, particularly in packets that are meant to be outgoing. As these should always be 0, wouldn't it make sense to omit these values from the structs and hard code them to always be 0?

https://github.com/eminence/lifx/blob/08526bb6bb260be75fa1f5e90904f1643050fff2/lifx-core/src/lib.rs#L975

**Comment by eminence** [comment]
You're right that they should always be zero when sending outgoing packets.  This is documented [here](https://docs.rs/lifx-core/latest/lifx_core/#reserved-fields) and [here](https://lan.developer.lifx.com/docs/field-types#reserved)

But it's sometimes interesting to see what non-zero values the official LIFX bulbs/apps set, so these fields are exposed.

**Comment by brianmay** [comment]
Hmmm. It does mean when constructing an outgoing packet, you need to explicitly set them to 0. But trivial issue. Will close, as there is a good reason for doing it this way.

**Comment by eminence** [comment]
Note:  The `lifx-core` library is pretty low-level, which is why these fields are exposed.  A higher-level `lifx` library (which doesn't exist yet) wouldn't expose these reserved fields, and would be able to ensure they are always zeroed
